script_dir <- dirname(normalizePath(sub("--file=", "", commandArgs(FALSE)[grepl("--file=", commandArgs(FALSE))]), mustWork = TRUE))
source(file.path(script_dir, "00_setup_oncology_module.R"))
message("Tumor mapping is generated by 01_oncology_analysis_pipeline.R.")
if (!file.exists(file.path(ROOT, "02_oncology_scope_and_tumor_mapping/oncology_tumor_term_mapping.csv"))) {
  system2("Rscript", file.path(script_dir, "01_oncology_analysis_pipeline.R"))
}
stopifnot(file.exists(file.path(ROOT, "02_oncology_scope_and_tumor_mapping/oncology_tumor_term_mapping.csv")))

