script_dir <- dirname(normalizePath(sub("--file=", "", commandArgs(FALSE)[grepl("--file=", commandArgs(FALSE))]), mustWork = TRUE))
source(file.path(script_dir, "00_setup_oncology_module.R"))
message("Tumor-death profiles are generated by 01_oncology_analysis_pipeline.R.")
if (!file.exists(file.path(ROOT, "04_tumor_specific_death_profiles/tumor_death_selectivity.csv"))) {
  system2("Rscript", file.path(script_dir, "01_oncology_analysis_pipeline.R"))
}
stopifnot(file.exists(file.path(ROOT, "04_tumor_specific_death_profiles/tumor_death_selectivity.csv")))

