script_dir <- dirname(normalizePath(sub("--file=", "", commandArgs(FALSE)[grepl("--file=", commandArgs(FALSE))]), mustWork = TRUE))
source(file.path(script_dir, "00_setup_oncology_module.R"))
message("Same-drug multi-death signal table is generated by 01_oncology_analysis_pipeline.R.")
if (!file.exists(file.path(ROOT, "07_same_drug_multi_death_signals/drug_polydeath_signal_table.csv"))) {
  system2("Rscript", file.path(script_dir, "01_oncology_analysis_pipeline.R"))
}
stopifnot(file.exists(file.path(ROOT, "07_same_drug_multi_death_signals/drug_polydeath_signal_table.csv")))

