script_dir <- dirname(normalizePath(sub("--file=", "", commandArgs(FALSE)[grepl("--file=", commandArgs(FALSE))]), mustWork = TRUE))
source(file.path(script_dir, "00_setup_oncology_module.R"))
message("Therapy-class landscape is generated by 01_oncology_analysis_pipeline.R.")
if (!file.exists(file.path(ROOT, "08_therapy_class_landscape/therapy_class_death_mode_matrix.csv"))) {
  system2("Rscript", file.path(script_dir, "01_oncology_analysis_pipeline.R"))
}
stopifnot(file.exists(file.path(ROOT, "08_therapy_class_landscape/therapy_class_death_mode_matrix.csv")))

